name: "CI - Qualité du Code"

on:
  workflow_call:

jobs:
  quality-frontend:
    name: Lint & Qualité - Frontend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Configuration de Node.js avec Cache npm
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Installation des dépendances Frontend
        run: npm ci

      - name: Exécution du Linter ESLint
        run: npm run lint

  quality-backend:
    name: Lint & Qualité - API Backend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Configuration de Node.js avec Cache npm
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: api/package-lock.json

      - name: Installation des dépendances API
        working-directory: ./api
        run: npm install

      - name: Vérification de la syntaxe et du code API
        working-directory: ./api
        run: npm run lint
